version: "3.8"

name: "sindikat"

services:
        
  postgres:
    image: postgres:14.3-alpine
    container_name: sdkt.postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - sdkt

networks:
  sdkt:
    name: sdkt.network
